In [1]:
import numpy as np 

In [3]:
np.array([8, 4, 6, 0, 2]);

Problem 1.

In [6]:
def dot_prod():
    A = np.array([[3, -1, 4], [1, 5, -9]])
    B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]])
    AB = np.dot(A,B)
    return AB

In [8]:
dot_prod()

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

Problem 2.

In [12]:
def make_poly_A():
    A = np.array([[3, 1, 4], [1, 5, 4], [-5, 3, 1]])
    A2 = np.dot(A, A)
    A3 = np.dot(A2, A)
    poly_A = -A3 + 9*A2 - 15*A
    return poly_A

In [20]:
make_poly_A()

array([[-25,  15,  60],
       [ 15,   5,  60],
       [-75,  45, -55]])

Problem 3.

In [34]:
def ABA():    
    ones = np.ones_like(np.eye(7))
    A = np.triu(ones)
    neg_ones = np.tril(ones * (-1))
    fives = 5 * np.triu(ones)
    B = neg_ones + fives
    np.fill_diagonal(B, -1)
    ABA = A @ B @ A
    return ABA.astype(np.int64)

In [36]:
ABA()

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]], dtype=int64)

Problem 4.

In [41]:
# define a matrix that has some negative values
A = np.ones([7,7])
np.fill_diagonal(A, -3)
A

array([[-3.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1., -3.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1., -3.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., -3.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., -3.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1., -3.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1., -3.]])

In [50]:
def replace_neg_vals(matrix):
    B = np.copy(matrix)
    B[B <= 0] = 0
    return B

In [51]:
replace_neg_vals(A)

array([[ 0.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  0.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  0.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  0.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  0.]])

Problem 5.

In [91]:
def make_big_mat():
    '''
    Block matriy has the size 8x8
    shpes of the 0s are: 3x3, 2x2, 2x3 and 3x2
    '''
    
    A = np.arange(6).reshape((2,3))
    B = np.tril(np.full((3,3), 3))
    C = np.eye(3) * (-2)
    I = np.eye(3)
    
    row1 = np.hstack((np.zeros((3,3)), A.T, I))
    row2 = np.hstack((A, np.zeros((2,2)), np.zeros((2,3))))
    row3 = np.hstack((B, np.zeros((3, 2)), C))
    big_mat = np.vstack((row1, row2, row3))
    
    return big_mat.astype(np.int64)

make_big_mat()

array([[ 0,  0,  0,  0,  3,  1,  0,  0],
       [ 0,  0,  0,  1,  4,  0,  1,  0],
       [ 0,  0,  0,  2,  5,  0,  0,  1],
       [ 0,  1,  2,  0,  0,  0,  0,  0],
       [ 3,  4,  5,  0,  0,  0,  0,  0],
       [ 3,  0,  0,  0,  0, -2,  0,  0],
       [ 3,  3,  0,  0,  0,  0, -2,  0],
       [ 3,  3,  3,  0,  0,  0,  0, -2]], dtype=int64)

Problem 6.

In [96]:
def row_stoch(matrix):
    scale = A.sum(axis=1).reshape((3,1))
    stoch = A / scale
    return stoch

In [113]:
A = np.arange(15).reshape((3, 5))
A_stoch = row_stoch(A)
(A_stoch.sum(axis=1).round(0).astype(np.int64) == 1).all()

True

Problem 7.

In [122]:
# load the grid
grid = np.load(r"C:\Users\Max\Documents\BootCamp2017\Computation\Wk1_PyIntro\grid.npy")

In [150]:
def get_max_axis(matrix):
    # horizontal maximum 
    max_hor =  np.max(matrix[:,:-3] * matrix[:,1:-2] * matrix[:,2:-1] * matrix[:,3:])
    # vertical maximum 
    max_ver = np.max(matrix[:-3,:] * matrix[1:-2,:] * matrix[2:-1,:] * matrix[3:,:])
    # maximum right diagonal
    max_rdiag = np.max(matrix[:-3,:-3] * matrix[1:-2,1:-2] * matrix[2:-1,2:-1] * matrix[3:,3:])
    # maximum left diagonal 
    max_ldiag = np.max(matrix[3:,:-3] * matrix[2:-1, 1:-2] * matrix[1:-2,2:-1] * matrix[:-3,3:])
    return max_hor, max_ver, max_rdiag, max_ldiag

In [151]:
get_max_axis(grid)

(48477312, 51267216, 40304286, 70600674)